### ISSUE TITLE
הערות על המשחק

### ISSUE THREAD

**Issue by erelsgl** [Game-Dev-Baram-Chahine/student-at-ariel-game#1]
א. הפונט מאד קטן - כך לפחות זה נראה אצלי: 
![image](https://github.com/Game-Dev-Baram-Chahine/student-at-ariel-game/assets/1462215/dec07fa4-45e4-4c9b-bf11-f2e5bfa142cb)
צריך לדאוג לנגישות וקריאות.

ב. כשניסיתי להנחית את החללית, היא התנגשה בכוכב, ולא הבנתי למה, ומה בדיוק אני צריך לעשות כדי למנוע את זה. חשוב להוסיף הסברים

**Comment by ibrahimchahine** [comment]
1. הפונט עודכן בBUILD שיעלה היום 
2. הוספנו עוד הוראות למשחקים
