### ISSUE TITLE
כל פעם שמתחיל שלב השחק חוזר לאותו מקום

### ISSUE THREAD

**Issue by VictoKu1** [Game-Dev-Baram-Chahine/student-at-ariel-game#2]
בלי קשר למיקום שבו היה השחקן כשיוצאים ממנו, חוזרים לחצר של הבית שלו.

**Comment by VictoKu1** [comment]
במיקום של הבר אין שום דבר.

**Comment by VictoKu1** [comment]
בשלב עם הזריקה לפח כדאי להוסיף את האפשרות לצאת מהמשחק בלי לצאת מהמיקום שבו המשחק הופעל.

**Comment by VictoKu1** [comment]
בשלב עם החלליות כדאי להחליף את השליטה של הכפתורים למעלה ולמטה (או לתת את האפשרות להכנס להגדרות ולשנות לבד).

**Comment by VictoKu1** [comment]
כדאי להוסיף אוביקטים כלשהם כחסמים ב2 הצדדים של המפה כי אחרת השחקן סתם נעצר בלי סיבה.

**Comment by ibrahimchahine** [comment]
> בלי קשר למיקום שבו היה השחקן כשיוצאים ממנו, חוזרים לחצר של הבית שלו.

תוקן, עכשיו מתי שיוצאים מהבניין נשארים שם.

**Comment by ibrahimchahine** [comment]
> במיקום של הבר אין שום דבר.

האופציה להיכנס לבר נמחקה, כרגע אפשר להיכנס לבית, ספרייה או פקולטה

**Comment by ibrahimchahine** [comment]
> בשלב עם הזריקה לפח כדאי להוסיף את האפשרות לצאת מהמשחק בלי לצאת מהמיקום שבו המשחק הופעל.

הוספנו לכל משחק את האופציה לצאת ולהיות בבניין הנוכחי.

**Comment by ibrahimchahine** [comment]
> בשלב עם החלליות כדאי להחליף את השליטה של הכפתורים למעלה ולמטה (או לתת את האפשרות להכנס להגדרות ולשנות לבד).

השליטה בחללית הם עם הכפתורים למעלה ולמטה וימינה ושמאלה, יש גם מדריך לאיך להשתמש. אז החלטנו להשאיר לפי החצים.

**Comment by DorBaram** [comment]
> כדאי להוסיף אוביקטים כלשהם כחסמים ב2 הצדדים של המפה כי אחרת השחקן סתם נעצר בלי סיבה.

התווספו אובייקטים כחסמים בשני הצדדים
