### ISSUE TITLE
סימון לסוף יום

### ISSUE THREAD

**Issue by erelsgl** [Game-Dev-Baram-Chahine/student-at-ariel-game#3]
כרגע אין שום חיווי לשחקן על כך שהיום נגמר ומתחיל יום חדש (חוץ מזה שהטקסט הקטן עם שם היום מתחלף). כדאי להוסיף משהו, לדוגמה מסך מעבר שבו השחקן ישן / מתעורר ליום חדש, או רק טקסט שאומר שעכשיו יום שלישי.

**Comment by DorBaram** [comment]
חושבים על פתרון יצירתי לעניין, נעדכן בהמשך
