### ISSUE TITLE
בניינים ריקים

### ISSUE THREAD

**Issue by erelsgl** [Game-Dev-Baram-Chahine/student-at-ariel-game#4]
א. יש עוד כמה בניינים (עם דלת) שאי אפשר להיכנס אליהם. האם אפשר למחוק את הדלתות האלו?

ב. האם אפשר להוסיף שלט מעל כל בניין שאפשר להיכנס אליו (בית, ספריה, כיתה)?

**Comment by DorBaram** [comment]
> א. יש עוד כמה בניינים (עם דלת) שאי אפשר להיכנס אליהם. האם אפשר למחוק את הדלתות האלו?
> 
> ב. האם אפשר להוסיף שלט מעל כל בניין שאפשר להיכנס אליו (בית, ספריה, כיתה)?

א. בגירסה שעלתה עכשיו הורדו הדלתות שלא מתשמשים בהם 
ב. אפשרי, עודכן בגירסה החדשה
